# Generated by Django 3.1.7 on 2021-03-08 10:18

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='image',
            field=models.ImageField(upload_to=properties.models.agent_image_upload_directory_path),
        ),
        migrations.AlterField(
            model_name='alerproperty',
            name='image1',
            field=models.ImageField(upload_to=properties.models.property_image_upload_directory_path),
        ),
        migrations.AlterField(
            model_name='alerproperty',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.property_image_upload_directory_path),
        ),
        migrations.AlterField(
            model_name='alerproperty',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.property_image_upload_directory_path),
        ),
    ]
