# Generated by Django 3.1.7 on 2021-03-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20210308_1318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyTypes',
            new_name='PropertyType',
        ),
    ]
