# Generated by Django 3.1.7 on 2021-03-08 10:50

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20210308_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerproperty',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to=properties.models.property_image_upload_directory_path),
        ),
    ]
