# Generated by Django 3.1.7 on 2021-03-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
